/**
 * Copyright (c) 2023-present Plane Software, Inc. and contributors
 * SPDX-License-Identifier: AGPL-3.0-only
 * See the LICENSE file for details.
 */

import { useEffect, useMemo } from "react";
// plane imports
import { COMMENT_MARK_ID_ATTRIBUTE } from "@plane/editor";
// local imports
import { usePageCommentsContext } from "./context";

// anchor ids are generated by the app; anything else is never written into a selector
const SAFE_ANCHOR_ID = /^[\w-]+$/;

/**
 * Highlights the page text that open comment threads are anchored to, and opens a thread when its text is
 * clicked. Resolved and deleted threads keep their (invisible) mark in the page.
 */
export function PageCommentHighlights() {
  const context = usePageCommentsContext();
  const threads = context?.threads;
  const activeThreadId = context?.activeThreadId;
  const setActiveThreadId = context?.setActiveThreadId;
  const openCommentsPane = context?.openCommentsPane;

  const openAnchors = useMemo(() => {
    const anchors = new Map<string, string>();
    for (const { root } of threads ?? []) {
      if (root.anchor_id && !root.resolved_at && SAFE_ANCHOR_ID.test(root.anchor_id))
        anchors.set(root.anchor_id, root.id);
    }
    return anchors;
  }, [threads]);

  const activeAnchorId = useMemo(
    () => threads?.find(({ root }) => root.id === activeThreadId)?.root.anchor_id ?? null,
    [threads, activeThreadId]
  );

  useEffect(() => {
    if (!setActiveThreadId || !openCommentsPane) return;
    const handleClick = (event: MouseEvent) => {
      const target = event.target as HTMLElement | null;
      const mark = target?.closest?.(`.editor-container [${COMMENT_MARK_ID_ATTRIBUTE}]`);
      const anchorId = mark?.getAttribute(COMMENT_MARK_ID_ATTRIBUTE);
      const threadId = anchorId ? openAnchors.get(anchorId) : undefined;
      if (!threadId) return;
      setActiveThreadId(threadId);
      openCommentsPane();
    };
    document.addEventListener("click", handleClick);
    return () => document.removeEventListener("click", handleClick);
  }, [openAnchors, openCommentsPane, setActiveThreadId]);

  if (openAnchors.size === 0) return null;

  const selector = (anchorId: string) => `.editor-container [${COMMENT_MARK_ID_ATTRIBUTE}="${anchorId}"]`;
  const css = [
    `${[...openAnchors.keys()].map(selector).join(",")}{background-color:var(--editor-colors-orange-background);border-bottom:2px solid var(--editor-colors-orange-text);cursor:pointer;}`,
    activeAnchorId && openAnchors.has(activeAnchorId)
      ? `${selector(activeAnchorId)}{background-color:var(--editor-colors-peach-background);}`
      : "",
  ].join("");

  return <style>{css}</style>;
}
